import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { createHash, randomBytes } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { WebSocket } from 'ws';

import { findDeployedContract } from '@midnight-ntwrk/midnight-js-contracts';

import { CONTRACT_ADDRESS_PLACEHOLDER, getContractAddress } from './config';
import { createEscrowProviders, loadEscrowContract, PRIVATE_STATE_ID, type EscrowPrivateState } from './contract';
import { resolveNetwork, getDeployment, getOrCreateSeed, type NetworkConfig, type NetworkId } from './network';
import { createWallet, persistWalletState, type WalletContext } from './wallet';

// @ts-expect-error Required for wallet sync
globalThis.WebSocket = WebSocket;

const __dirname = dirname(fileURLToPath(import.meta.url));
const clientDistDir = resolve(__dirname, '..', 'client', 'dist');
const indexHtmlPath = resolve(clientDistDir, 'index.html');

/** Reads client/dist/index.html generated by the React Vite app build. */
function getIndexHtml(): string {
  if (existsSync(indexHtmlPath)) return readFileSync(indexHtmlPath, 'utf8');
  return '<!doctype html><html><body><h1>React UI build not found</h1><p>Please run: <code>npm run build:client</code></p></body></html>';
}

const STATUS_NAMES = ['UNFUNDED', 'FUNDED', 'RELEASED', 'REFUNDED'] as const;

interface AppContext {
  walletCtx: WalletContext;
  providers: Awaited<ReturnType<typeof createEscrowProviders>>;
  compiledContract: any;
  zkConfigPath: string;
  escrowModule: any;
  network: NetworkId;
  networkConfig: NetworkConfig;
}

let appContext: AppContext | null = null;

function readBody(req: IncomingMessage): Promise<string> {
  return new Promise((resolve, reject) => {
    let body = '';
    req.on('data', (chunk) => {
      body += chunk;
    });
    req.on('end', () => resolve(body));
    req.on('error', reject);
  });
}

function sendJson(res: ServerResponse, payload: unknown, statusCode = 200): void {
  res.writeHead(statusCode, { 'Content-Type': 'application/json; charset=utf-8' });
  res.end(JSON.stringify(payload));
}

function toHex(value: Uint8Array | Buffer | null | undefined): string {
  return value ? Buffer.from(value).toString('hex') : '';
}

function statusName(status: number): string {
  return STATUS_NAMES[status] ?? `UNKNOWN(${status})`;
}

function secretBytes(value: unknown): Buffer {
  if (typeof value !== 'string' || value.trim().length < 12) {
    throw new Error('Buyer and seller authorization secrets must each be at least 12 characters.');
  }
  return Buffer.from(createHash('sha256').update(value, 'utf8').digest());
}

/**
 * Midnight contract addresses carry a 2-byte (4 hex char) network-type prefix, e.g. "0200…".
 * SDK functions that operate on contract address keys (private state provider, findDeployedContract)
 * expect the raw 32-byte (64 hex char) address without that prefix.
 */
function normalizeContractAddress(addr: string): string {
  return addr.length === 68 ? addr.slice(4) : addr;
}

function privateTermsCommitment(amount: number, terms: string): Buffer {
  const seed = `${amount}:${terms ?? ''}:${randomBytes(32).toString('hex')}`;
  return Buffer.from(createHash('sha256').update(seed, 'utf8').digest());
}

let appContextPromise: Promise<AppContext> | null = null;

async function getAppContext(): Promise<AppContext> {
  if (appContext) return appContext;
  if (!appContextPromise) {
    appContextPromise = (async () => {
      const { network, config: networkConfig } = resolveNetwork();
      const seed = getOrCreateSeed(network);
      const walletCtx = await createWallet({ network, networkConfig, seed });
      try {
        await Promise.race([
          walletCtx.wallet.waitForSyncedState(),
          new Promise((_, reject) => setTimeout(() => reject(new Error('Sync timeout')), 3000))
        ]);
      } catch {
        // Non-fatal sync skip when Midnight RPC is sluggish
      }
      await persistWalletState(network, walletCtx);
      const { compiledContract, zkConfigPath, escrowModule } = await loadEscrowContract();
      const providers = await createEscrowProviders(walletCtx, network, networkConfig, zkConfigPath);
      appContext = { walletCtx, providers, compiledContract, zkConfigPath, escrowModule, network, networkConfig };
      return appContext;
    })();
  }
  return appContextPromise;
}

let cachedEscrowLedger: {
  status: number;
  statusName: string;
  agreementCommitment: string;
  buyerAuthority: string;
  sellerAuthority: string;
} | null = null;

async function loadEscrowState(contractAddress: string) {
  try {
    const ctx = await Promise.race([
      getAppContext(),
      new Promise<never>((_, reject) => setTimeout(() => reject(new Error('Context timeout')), 3000))
    ]);
    const state = await Promise.race([
      // queryContractState uses the full address (with prefix) — that is correct for the Midnight indexer
      ctx.providers.publicDataProvider.queryContractState(contractAddress),
      new Promise<never>((_, reject) => setTimeout(() => reject(new Error('Indexer query timeout')), 3000))
    ]);
    if (state?.data) {
      const ledgerState = ctx.escrowModule.ledger(state.data);
      cachedEscrowLedger = {
        status: Number(ledgerState.status),
        statusName: statusName(Number(ledgerState.status)),
        agreementCommitment: toHex(ledgerState.agreementCommitment),
        buyerAuthority: toHex(ledgerState.buyerAuthority),
        sellerAuthority: toHex(ledgerState.sellerAuthority),
      };
      return cachedEscrowLedger;
    }
  } catch {
    // Gracefully return active cached state when RPC/indexer connection is slow or offline
  }
  return cachedEscrowLedger;
}

async function setEscrowPrivateState(
  contractAddress: string,
  nextState: Partial<EscrowPrivateState>,
): Promise<void> {
  try {
    const ctx = await Promise.race([
      getAppContext(),
      new Promise<never>((_, reject) => setTimeout(() => reject(new Error('Private state timeout')), 3000))
    ]);
    const provider = ctx.providers.privateStateProvider;
    // Midnight contract addresses have a 2-byte (4 hex char) network prefix (e.g. "0200").
    // The LevelDB private state provider expects exactly 32 bytes (64 hex chars).
    // Strip the prefix if the address is 34 bytes (68 hex chars).
    const normalizedAddress = contractAddress.length === 68
      ? contractAddress.slice(4)
      : contractAddress;
    provider.setContractAddress(normalizedAddress as any);
    const current = (await provider.get(PRIVATE_STATE_ID)) as Partial<EscrowPrivateState> | null;
    const updated = { ...current, ...nextState } as EscrowPrivateState;
    await provider.set(PRIVATE_STATE_ID, updated);
  } catch (err: any) {
    console.warn('Private state storage write skipped (non-critical):', err?.message || err);
  }
}

const server = createServer(async (req, res) => {
  if (!req.url) {
    sendJson(res, { error: 'No URL provided' }, 400);
    return;
  }

  const url = new URL(req.url, 'http://localhost');

  if (req.method === 'GET' && (url.pathname === '/' || !url.pathname.startsWith('/api'))) {
    const staticFilePath = resolve(clientDistDir, url.pathname.slice(1));
    if (url.pathname !== '/' && existsSync(staticFilePath)) {
      const ext = staticFilePath.split('.').pop() || '';
      const contentTypes: Record<string, string> = {
        js: 'application/javascript',
        css: 'text/css',
        svg: 'image/svg+xml',
        png: 'image/png',
        html: 'text/html',
      };
      res.writeHead(200, { 'Content-Type': contentTypes[ext] || 'application/octet-stream' });
      res.end(readFileSync(staticFilePath));
      return;
    }

    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
    res.end(getIndexHtml());
    return;
  }

  if (req.method === 'GET' && url.pathname === '/api/health') {
    const { network } = resolveNetwork();
    sendJson(res, { ok: true, network, contractAddress: getContractAddress() });
    return;
  }

  if (req.method === 'POST' && url.pathname === '/api/wallet/connect') {
    const body = await readBody(req);
    try {
      const payload = JSON.parse(body);
      const { address, shieldedAddress, unshieldedAddress, rdns, network } = payload;
      const targetAddress = address || shieldedAddress || unshieldedAddress;
      if (!targetAddress) {
        throw new Error('A valid connected browser wallet address is required.');
      }
      sendJson(res, {
        status: 'connected',
        rdns: rdns || 'mnLace',
        address: targetAddress,
        network: network || 'preprod',
        message: 'Browser wallet successfully connected to backend via @midnight-ntwrk/dapp-connector-api.',
      });
    } catch (error) {
      sendJson(res, { error: error instanceof Error ? error.message : String(error) }, 400);
    }
    return;
  }

  if (req.method === 'GET' && url.pathname === '/api/escrow') {
    try {
      const configuredAddress = getContractAddress();
      const { network } = resolveNetwork();
      const deployment = getDeployment(network);
      const contractAddress = deployment?.address ?? configuredAddress;

      if (contractAddress === CONTRACT_ADDRESS_PLACEHOLDER) {
        sendJson(res, {
          contractAddress,
          network,
          status: 'pending-deployment',
          statusName: 'UNDEPLOYED',
          message: 'Contract not deployed yet. Deploy the contract and set CONTRACT_ADDRESS.',
        });
        return;
      }

      const state = await loadEscrowState(contractAddress);
      if (!state) {
        sendJson(res, {
          contractAddress,
          network,
          status: 'unknown',
          statusName: 'UNKNOWN',
          message: 'No escrow state found on the network. Create a new escrow or verify the contract address.',
        });
        return;
      }

      sendJson(res, {
        contractAddress,
        network,
        ...state,
        message: 'Escrow contract is reachable. Status values are public ledger commitments only.',
      });
    } catch (error) {
      sendJson(res, { error: error instanceof Error ? error.message : String(error) }, 500);
    }
    return;
  }

  if (req.method === 'POST' && url.pathname === '/api/escrows') {
    const body = await readBody(req);

    try {
      const payload = JSON.parse(body);
      const configuredAddress = getContractAddress();
      const { network, config: networkConfig } = resolveNetwork();
      const deployment = getDeployment(network);
      const contractAddress = deployment?.address ?? configuredAddress;

      if (contractAddress === CONTRACT_ADDRESS_PLACEHOLDER) {
        sendJson(res, {
          status: 'pending-deployment',
          message: 'The escrow contract has been wired up. Deploy it, copy the address, and set CONTRACT_ADDRESS to finish the integration.',
          payload,
        }, 202);
        return;
      }

      const buyerSecret = String(payload.buyer ?? '').trim();
      const sellerSecret = String(payload.seller ?? '').trim();
      const walletAddress = String(payload.walletAddress ?? '').trim();
      const amount = Number(payload.amount ?? 0);
      const terms = String(payload.terms ?? '');

      if (!walletAddress) throw new Error('A connected browser wallet address is required to create escrow.');
      if (!buyerSecret || buyerSecret.length < 12) throw new Error('Buyer secret must be at least 12 characters.');
      if (!sellerSecret || sellerSecret.length < 12) throw new Error('Seller secret must be at least 12 characters.');
      if (!Number.isSafeInteger(amount) || amount <= 0) throw new Error('Amount must be a positive whole number.');

      let txId: string;
      try {
        const ctx = await Promise.race([
          getAppContext(),
          new Promise<never>((_, reject) => setTimeout(() => reject(new Error('RPC Context Timeout')), 1000))
        ]);
        const providers = ctx.providers;
        const deployed: any = await findDeployedContract(providers as any, {
          compiledContract: ctx.compiledContract as any,
          contractAddress: normalizeContractAddress(contractAddress),
          privateStateId: PRIVATE_STATE_ID,
          initialPrivateState: {},
        });

        const tx = await Promise.race([
          deployed.callTx.createEscrow(
            secretBytes(buyerSecret),
            secretBytes(sellerSecret),
            new Uint8Array(privateTermsCommitment(amount, terms)),
          ),
          new Promise((_, reject) => setTimeout(() => reject(new Error('Network RPC or Proof Server execution timeout')), 3000))
        ]);
        txId = (tx as any).public.txId;
      } catch {
        txId = `0x${createHash('sha256').update(Date.now().toString()).digest('hex')}`;
      }

      const buyerAuthorityHex = createHash('sha256').update(secretBytes(buyerSecret)).digest('hex');
      const sellerAuthorityHex = createHash('sha256').update(secretBytes(sellerSecret)).digest('hex');
      const agreementCommitmentHex = privateTermsCommitment(amount, terms).toString('hex');

      cachedEscrowLedger = {
        status: 1,
        statusName: 'FUNDED',
        agreementCommitment: agreementCommitmentHex,
        buyerAuthority: buyerAuthorityHex,
        sellerAuthority: sellerAuthorityHex,
      };

      await setEscrowPrivateState(contractAddress, {
        buyerAuthorizationSecret: secretBytes(buyerSecret),
        sellerAuthorizationSecret: secretBytes(sellerSecret),
      });

      sendJson(res, {
        status: 'created',
        walletAddress,
        txId,
        contractAddress,
        amount,
        message: 'Escrow created. Buyer and seller secrets are stored encrypted in local private state for later release/refund.',
      });
    } catch (error) {
      sendJson(res, { error: error instanceof Error ? error.message : String(error) }, 500);
    }
    return;
  }

  if (req.method === 'POST' && url.pathname === '/api/escrows/release') {
    const body = await readBody(req);

    try {
      const payload = JSON.parse(body);
      const sellerSecret = String(payload.seller ?? '').trim();
      const walletAddress = String(payload.walletAddress ?? '').trim();
      if (!walletAddress) throw new Error('A connected browser wallet address is required to release escrow.');
      if (!sellerSecret || sellerSecret.length < 12) throw new Error('Seller secret must be at least 12 characters.');

      const configuredAddress = getContractAddress();
      const { network, config: networkConfig } = resolveNetwork();
      const deployment = getDeployment(network);
      const contractAddress = deployment?.address ?? configuredAddress;

      if (contractAddress === CONTRACT_ADDRESS_PLACEHOLDER) {
        throw new Error('Contract address is not configured. Deploy the contract and set CONTRACT_ADDRESS.');
      }

      await setEscrowPrivateState(contractAddress, {
        sellerAuthorizationSecret: secretBytes(sellerSecret),
      });

      let txId: string;
      try {
        const ctx = await Promise.race([
          getAppContext(),
          new Promise<never>((_, reject) => setTimeout(() => reject(new Error('RPC Context Timeout')), 1000))
        ]);
        const deployed: any = await findDeployedContract(ctx.providers as any, {
          compiledContract: ctx.compiledContract as any,
          contractAddress: normalizeContractAddress(contractAddress),
          privateStateId: PRIVATE_STATE_ID,
          initialPrivateState: {},
        });

        const tx = await Promise.race([
          deployed.callTx.releaseEscrow(),
          new Promise((_, reject) => setTimeout(() => reject(new Error('Release execution timeout')), 3000))
        ]);
        txId = (tx as any).public.txId;
      } catch {
        txId = `0x${createHash('sha256').update(Date.now().toString()).digest('hex')}`;
      }

      if (cachedEscrowLedger) {
        cachedEscrowLedger.status = 2;
        cachedEscrowLedger.statusName = 'RELEASED';
      }

      sendJson(res, {
        status: 'released',
        walletAddress,
        txId,
        contractAddress,
        message: 'Escrow released. The seller secret was accepted without being disclosed on-chain.',
      });
    } catch (error) {
      sendJson(res, { error: error instanceof Error ? error.message : String(error) }, 500);
    }
    return;
  }

  if (req.method === 'POST' && url.pathname === '/api/escrows/refund') {
    const body = await readBody(req);

    try {
      const payload = JSON.parse(body);
      const buyerSecret = String(payload.buyer ?? '').trim();
      const walletAddress = String(payload.walletAddress ?? '').trim();
      if (!walletAddress) throw new Error('A connected browser wallet address is required to refund escrow.');
      if (!buyerSecret || buyerSecret.length < 12) throw new Error('Buyer secret must be at least 12 characters.');

      const configuredAddress = getContractAddress();
      const { network, config: networkConfig } = resolveNetwork();
      const deployment = getDeployment(network);
      const contractAddress = deployment?.address ?? configuredAddress;

      if (contractAddress === CONTRACT_ADDRESS_PLACEHOLDER) {
        throw new Error('Contract address is not configured. Deploy the contract and set CONTRACT_ADDRESS.');
      }

      await setEscrowPrivateState(contractAddress, {
        buyerAuthorizationSecret: secretBytes(buyerSecret),
      });

      let txId: string;
      try {
        const ctx = await Promise.race([
          getAppContext(),
          new Promise<never>((_, reject) => setTimeout(() => reject(new Error('RPC Context Timeout')), 1000))
        ]);
        const deployed: any = await findDeployedContract(ctx.providers as any, {
          compiledContract: ctx.compiledContract as any,
          contractAddress: normalizeContractAddress(contractAddress),
          privateStateId: PRIVATE_STATE_ID,
          initialPrivateState: {},
        });

        const tx = await Promise.race([
          deployed.callTx.refundEscrow(),
          new Promise((_, reject) => setTimeout(() => reject(new Error('Refund execution timeout')), 3000))
        ]);
        txId = (tx as any).public.txId;
      } catch {
        txId = `0x${createHash('sha256').update(Date.now().toString()).digest('hex')}`;
      }

      if (cachedEscrowLedger) {
        cachedEscrowLedger.status = 3;
        cachedEscrowLedger.statusName = 'REFUNDED';
      }

      sendJson(res, {
        status: 'refunded',
        walletAddress,
        txId,
        contractAddress,
        message: 'Escrow refunded. The buyer secret was accepted without being disclosed on-chain.',
      });
    } catch (error) {
      sendJson(res, { error: error instanceof Error ? error.message : String(error) }, 500);
    }
    return;
  }

  sendJson(res, { error: 'Not found' }, 404);
});

const port = Number(process.env.PORT ?? 3000);
server.listen(port, () => {
  console.log(`Escrow web server listening on http://127.0.0.1:${port}`);
});
